const ACTION = {
    //get profile
    GET_USER_PROFILE: "GET_USER_PROFILE",
    GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS", // KATA MAS GERIS INI PROTOKOL

    //doctor
    GET_CLINIC_DOCTOR: "GET_CLINIC_DOCTOR",
    GET_CLINIC_DOCTOR_SUCCESS: "GET_CLINIC_DOCTOR_SUCCESS",
};
export default ACTION;
